RegisterNetEvent('Braquage:Alerte')
AddEventHandler('Braquage:Alerte', function(Coords)
    CreateThread(function()
        local Blip = AddBlipForCoord(Coords.x, Coords.y, Coords.z)
        SetBlipSprite(Blip, 4)
        SetBlipScale(Blip, 0.3)
        SetBlipColour(Blip, 1)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentString('Demande de renfort(s)')
        EndTextCommandSetBlipName(Blip)
        SetBlipAsShortRange(Blip, true)
        PlaySoundFrontend(-1, "TIMER_STOP", "HUD_MINI_GAME_SOUNDSET", 1)

        SetTimeout(40000, function()
            RemoveBlip(Blip)
        end)
        
    end)
end)